from django.urls import path
from . import views
from django.urls import path
from . import views
from django.urls import path, include
from .views import (
    home,
    pricing,
    contact,
    visualize,
    signinn,
    signup,
    signout,
    services,
    payment,
    confusion_matrix,
    roc_auc,
    dataset,
    error_analysis,
    dataset_description,
    fully_responsive,
    fresh_layout,
    minimalism_feast,
    modern_workflow,
    unique_feature,
    support,
    contact_form,
    visualize_page,
    data_process,
    ocr,
    data_cleaning,
    preprocess_csv,
    cleaning,
    chat_form,
    terms_condition,
    faq,
    blog,
    team,
    plotting,
    charge,


)


urlpatterns = [

    path('', home, name='home'),
    path('pricing', pricing, name='pricing'),
    path('contact', contact, name='contact'),
    path('visualize/', visualize, name='visualize'),
    path('data_process/', data_process, name='data_process'),
    path('signin/',signinn,name="signin"),
    path('signup/',signup,name="signup"),
    path('signout/',signout,name="signout"),
    path('services/',services,name="services"),
    path('payment/',payment,name="payment"),
    path('confusion_matrix/',confusion_matrix,name="confusion_matrix"),
    path('roc_auc/',roc_auc,name="roc_auc"),
    path('dataset/',dataset,name="dataset"),
    path('error_analysis/',error_analysis,name="error_analysis"),
    path('dataset_description/',dataset_description,name="dataset_description"),
    path('fully_responsive/',fully_responsive,name="fully_responsive"),
    path('fresh_layout/',fresh_layout,name="fresh_layout"),
    path('minimalism_feast/',minimalism_feast,name="minimalism_feast"),
    path('modern_workflow/',modern_workflow,name="modern_workflow"),
    path('unique_feature/',unique_feature,name="unique_feature"),
    path('support/',support,name="support"),
    path('contact_form/',contact_form,name="contact_form"),
    path('visualize_page/',visualize_page,name="visualize_page"),
    path('ocr/', views.OCR, name='OCR'),
    path('ocr/', views.ocr, name='ocr'),
    path('chat/', views.chat, name='chat'),
    path('data_cleaning/', views.data_cleaning, name='data_cleaning'),
    path('preprocess_csv/', views.preprocess_csv, name='preprocess_csv'),
    path('cleaning/', views.cleaning, name='cleaning'),
    path('chat_form', chat_form, name='chat_form'),
    path('terms_condition', terms_condition, name='terms_condition'),
    path('faq', faq, name='faq'),
    path('charge/', charge, name='charge'),
    path('blog/', blog, name='blog'),
    path('team/', team, name='team'),
    path('plotting/', plotting, name='plotting'),
]
