# Generated by Django 4.1.6 on 2023-03-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('phone', models.CharField(max_length=99)),
                ('email', models.CharField(max_length=99)),
                ('company', models.CharField(max_length=99)),
                ('message', models.TextField(max_length=99)),
            ],
        ),
    ]
